# =============================================================
# Scraper configuration — EatEatEat multi-city
#
# Add new cities to the CITIES dict below.
# The backward-compat aliases at the bottom keep pipeline.py
# working without any changes (defaults to Mallorca).
# =============================================================

CITIES = {
    "mallorca": {
        "db_id": 1,
        "name": "Mallorca",
        "search_terms": [
            "Specialty Coffee",
            "Brunch",
            "Wine Bar",
            "Weingut",
            "Weinprobe",
            "Bodega",
            "Vermuteria",
            "Restaurant",
            "Kaffee und Kuchen",
            "Chiringuito",
            "Tapas modern",
            "Farm to table",
            "Rooftop bar",
            "Boutique hotel restaurant",
            "Sommelier",
            "Open kitchen",
            "Romantic terrace",
            "Dachterrasse",
            "Great view Restaurant",
            "Pa Amb Oli",
            "Mandelkuchen",
            "familiengeführtes restaurant",
            "Slow food",
            "Cocina mallorquina",
            "Ensaimada artesanal",
            "Natural wine bar",
            "Aperitivo",
            "Garden restaurant",
            "Sushi restaurant",
            "Fusion restaurant",
            "Agroturismen restaurant",
            "Meerview restaurant",
            "Mexican/taco restaurant",
        ],
        "locations": [
            "Mallorca",
            "Palma de Mallorca",
            "Portixol, Palma de Mallorca",
            "Santa Catalina, Palma de Mallorca",
            "Alaró, Mallorca",
            "Sóller, Mallorca",
            "port de Sóller, Mallorca",
            "Pollença, Mallorca",
            "Deià, Mallorca",
            "Inca, Mallorca",
            "Santa Maria del Camí, Mallorca",
            "Binissalem, Mallorca",
            "Santa Eugenia, Mallorca",
            "Santanyí, Mallorca",
            "Sencelles, Mallorca",
            "Esporles, Mallorca",
            "Sineu, Mallorca",
            "Port de Andratx, Mallorca",
            "Alcúdia, Mallorca",
            "Can Picafort, Mallorca",
            "Port de pollença, Mallorca",
            "Santa ponça, Mallorca",
            "palmanova, Mallorca",
            "portals nous, Mallorca",
            "port de andratx, Mallorca",
            "andratx, Mallorca",
            "Bunyola, Mallorca",
            "Orient, Mallorca",
            "Ma-10, Mallorca",
            "Casco Antiguo Mallorca",
            "La Lonja Mallorca",
            "Molinar Mallorca",
            "El Terreno Mallorca",
            "Passeig del Born Mallorca",
            "Jaime III Mallorca",
            "Cala Major Mallorca",
            "Pere Garau Mallorca",
            "Son Armadams Mallorca",
            "Son Vida Mallorca",
            "Selva, Mallorca",
            "Consell, Mallorca",
            "Biniagual, Mallorca",
            "Costitx, Mallorca",
            "Llubi, Mallorca",
            "Maria de la Salut, Mallorca",
            "Ariany, Mallorca",
            "Petra, Mallorca",
            "Vilafranca de Bonany, Mallorca",
            "Porreres, Mallorca",
            "Montuiri, Mallorca",
            "Algaida, Mallorca",
            "Randa, Mallorca",
            "Llucmajor inland, Mallorca",
            "Campos inland, Mallorca",
            "Sant Joan, Mallorca",
            "Santa Margalida inland, Mallorca",
            "Muro inland, Mallorca",
            "Campanet, Mallorca",
            "Sa Pobla, Mallorca",
            "Buger, Mallorca",
            "Caimari, Mallorca",
            "Mancor de la Vall, Mallorca",
            "Lloseta, Mallorca",
            "Valldemossa, Mallorca",
            "Banyalbufar, Mallorca",
            "Estellencs, Mallorca",
            "Fornalutx, Mallorca",
            "Lluc, Mallorca",
            "Escorca, Mallorca",
            "Sa Calobra, Mallorca",
            "Torrent de Pareis, Mallorca",
            "Port de Valldemossa, Mallorca",
            "Cala Deià, Mallorca",
            "Sa Foradada, Mallorca",
            "Son Marroig, Mallorca",
            "Mirador de Ses Barques, Mallorca",
            "Coll de Sóller, Mallorca",
            "Puigpunyent, Mallorca",
            "Galilea, Mallorca",
            "Calvià village, Mallorca",
            "Es Capdellà, Mallorca",
            "Andratx village, Mallorca",
            "Sant Elm, Mallorca",
            "La Trapa, Mallorca",
            "Cap de Formentor, Mallorca",
            "Cala Tuent, Mallorca"
        ],
        "min_rating": 4.5,
        "min_rating_count": 100,
        "search_language": "de",
        "search_country": "es",
    },

    "stuttgart": {
        "db_id": 2,
        "name": "Stuttgart",
        "search_terms": [
            "Restaurant",
            "Weinbar",
            "Brunch",
            "Whisky",
            "Specialty Coffee",
            "Fine Dining",
            "Michelin Stern",
            "Bistro",
            "Tapas",
            "Sushi",
            "Steakhouse",
            "Burger",
            "Vegetarisch",
            "Vegan",
            "Arabisch",
            "Afrikanisch",
            "Griechisch",
            "Italienisch",
            "Koreanisch",
            "Asiatisch",
            "Bar",
            "Rooftop Bar",
            "Cocktailbar",
            "Bäckerei Café",
            "Frühstück",
            "Mittagstisch",
            "Biergarten",
            "Weingut mit Restaurant",
            "Eis Café",
            "Besenwirtschaften"
        ],
        "locations": [
            "Stuttgart",
            "Stuttgart-Mitte",
            "Stuttgart-West",
            "Stuttgart-Süd",
            "Stuttgart-Nord",
            "Stuttgart-Ost",
            "Bohnenviertel Stuttgart",
            "Leonhardsviertel Stuttgart",
            "Hospitalviertel Stuttgart",
            "Lehen, Stuttgart",
            "Marktplatz Stuttgart",
            "Königstraße Stuttgart",
            "Calwer Straße Stuttgart",
            "Rotebühlplatz Stuttgart",
            "Heusteigviertel Stuttgart",
            "Stuttgarter Weinsteige",
            "Gabelnberg Stuttgart",
            "Killesberg Stuttgart",
            "Remstal bei Stuttgart",
            "Degeloch Stuttgart",
            "Neckar Stuttgart",
            "Bad Cannstatt Stuttgart",
            "Feuerbach Stuttgart",
            "Vaihingen Stuttgart",
            "pliningen/Hohenheim Stuttgart",
            "Zuffenhausen Stuttgart",
            "Möhringen Stuttgart",
            "Marienplatz Stuttgart",
            "Schwabstraße Stuttgart",
        ],
        "min_rating": 4.3,
        "min_rating_count": 50,
        "search_language": "de",
        "search_country": "de",
    },

    "london": {
        "db_id": 3,
        "name": "London",
        "search_terms": [
            "Restaurant",
            "Gastropub",
            "Beer bruwery",
            "pub",
            "Sunday Roast",
            "Afternoon Tea",
            "Modern British",
            "Brunch",
            "Specialty Coffee",
            "Fine Dining",
            "Tasting Menu",
            "Omakase",
            "Small Plates",
            "Natural Wine Bar",
            "Wine Bar",
            "Cocktail Bar",
            "Rooftop Bar",
            "Speakeasy",
            "Whisky Bar",
            "Gin Bar",
            "Indian Restaurant",
            "Middle Eastern Restaurant",
            "Turkish Restaurant",
            "Vietnamese Restaurant",
            "Korean Restaurant",
            "Dim Sum",
            "Japanese Restaurant",
            "Israeli Restaurant",
            "West African Restaurant",
            "Italian Restaurant",
            "Pizza",
            "Street Food",
            "Pub Lunch",
            "Pie and Mash",
            "Farm-to-Table",
            "Seasonal British",
            "Nose-to-Tail",
            "Open Fire Cooking",
            "Wood Fired Restaurant",
            "Chef's Table",
            "Counter Dining",
            "BYOB Restaurant",
            "Pop-Up Restaurant",
            "Supper Club",
            "Food Market",
            "Street Food Market",
            "Food Hall",
            "Market Hall",
            "Borough Market Food",
            "Maltby Street Market",
            "Hackney Food Scene",
            "Shoreditch Restaurants",
            "Soho Dining",
            "Covent Garden Restaurants",
            "Mayfair Fine Dining",
            "Notting Hill Restaurants",
            "Brixton Village Food",
            "Dalston Restaurants",
            "Peckham Food Scene",
            "Canary Wharf Restaurants",
            "Michelin Star Restaurant",
            "Bib Gourmand",
            "Affordable Fine Dining",
            "Tasting Counter",
            "Degustation Menu",
            "Fusion Cuisine",
            "Asian Fusion",
            "Peruvian Restaurant",
            "Nikkei Cuisine",
            "Sri Lankan Restaurant",
            "Bangladeshi Restaurant",
            "Nepalese Restaurant",
            "Ethiopian Restaurant",
            "Caribbean Restaurant",
            "Jerk Chicken",
            "Salt Beef Bagel",
            "Jewish Deli",
            "Rooftop Restaurant",
            "Rooftop Bar",
            "Bagel Shop",
            "British Seafood",
            "Oyster Bar",
            "Fish Restaurant",
            "Chippy",
            "Fish and Chips",
            "Butcher Restaurant",
            "Steakhouse",
            "Sunday Lunch",
            "Bottomless Brunch",
            "Brunch Cafe",
            "Third Wave Coffee",
            "Coffee Roastery",
            "Dessert Bar",
            "Patisserie",
            "Bakery",
            "Artisan Bakery",
            "Sourdough Bakery",
            "Vegan Restaurant",
            "Vegetarian Restaurant",
            "Plant-Based Dining",
            "Gluten Free Restaurant",
            "Halal Restaurant",
            "Late Night Food",
            "24 Hour Restaurant",
            "Pre-Theatre Dining",
            "Post-Theatre Dining",
            "Chef Collaboration Dinner",
            "Experimental Dining",
            "Immersive Dining Experience",
            "Private Dining Room",
            "Riverside Dining",
            "Canal Side Cafe",
            "Hidden Gem Restaurant",
            "Institution Restaurant",
            "Classic London Restaurant",
        ],
        "locations": [
            # Märkte / Food Hubs
            "Borough Market London",
            "Maltby Street Market London",
            "Broadway Market London",
            "Netil Market London",
            "Seven Dials Market London",
            "Mercato Metropolitano London",
            "Market Halls Victoria London",
            "Market Halls Oxford Street London",
            "Arcade Food Hall London",
            "Flat Iron Square London",
            "Vinegar Yard London",
            "Dinerama Shoreditch London",
            "Boxpark Shoreditch London",
            "Boxpark Croydon London",
            "Pop Brixton London",
            "Pergola Paddington London",
            "Pergola on the Wharf London",

            # Straßen / Micro Food Streets
            "Exmouth Market London",
            "Bermondsey Street London",
            "Redchurch Street London",
            "Rivington Street London",
            "Curtain Road London",
            "Upper Street Islington London",
            "Brick Lane London",
            "Columbia Road London",

            # Plätze / Cluster
            "Coal Drops Yard London",
            "Granary Square London",
            "Neals Yard London",
            "Kingly Court London",
            "Duke of York Square London",

            # Wasser / Outdoor
            "South Bank London",
            "Regents Canal London",
            "Paddington Basin London",
            "Little Venice London",
            "Bankside London",
            "Waterloo London",

            # Core Central (hohe Dichte)
            "Soho London",
            "Fitzrovia London",
            "Marylebone London",
            "Covent Garden London",
            "Seven Dials London",
            "Bloomsbury London",
            "Holborn London",
            "St Jamess London",
            "Mayfair London",

            # East London (trendy / hohe Dynamik)
            "Shoreditch London",
            "Old Street London",
            "Hoxton London",
            "Haggerston London",
            "Dalston London",
            "London Fields London",
            "Hackney Central London",
            "Hackney Wick London",
            "Victoria Park London",
            "Bethnal Green London",
            "Spitalfields London",
            "Whitechapel London",
            "Mile End London",
            "Stratford London",

            # North / North-East
            "Angel London",
            "Islington London",
            "Highbury London",
            "Canonbury London",
            "Finsbury Park London",
            "Stoke Newington London",
            "Crouch End London",
            "Kentish Town London",
            "Camden London",
            "Tufnell Park London",
            "Green Lanes London",

            # South London (sehr relevant!)
            "Borough London",
            "London Bridge",
            "Bermondsey London",
            "Peckham London",
            "Peckham Rye London",
            "Peckham Levels London",
            "Rye Lane Peckham London",
            "Nunhead London",
            "East Dulwich London",
            "Dulwich Village London",
            "Brixton London",
            "Pop Brixton London",
            "Herne Hill London",
            "Clapham London",
            "Clapham Common London",
            "Battersea London",
            "Nine Elms London",
            "Tooting London",

            # West London (gehoben / etabliert)
            "Notting Hill London",
            "Westbourne Grove London",
            "Holland Park London",
            "Kensington London",
            "South Kensington London",
            "Earls Court London",
            "Chelsea London",
            "Fulham London",
            "Knightsbridge London",
            "Belgravia London",
            "Pimlico London",

            # Wealth / Residential High-End
            "St Johns Wood London",
            "Maida Vale London",
            "Primrose Hill London",
            "Lancaster Gate London",

            # Ethnic Food Power Zones (entscheidend!)
            "Chinatown London",
            "Edgware Road London",
            "Southall London",
            "Wembley London",
            "Golders Green London",
            "New Malden London",
            "Ilford London",

            # Emerging / Development
            "Kings Cross London",
            "Paddington London",
            "Canary Wharf London",
            "Wembley Park London",

            # Intent / Discovery Boost (für bessere Treffer)
            "best restaurants Soho London",
            "cool restaurants Shoreditch London",
            "hidden gems London food",
            "best brunch London areas",
            "trendy restaurants London neighborhoods",
            "where to eat East London",
            "food hotspots London"
        ],
        "min_rating": 4.5,
        "min_rating_count": 100,
        "search_language": "en",
        "search_country": "gb",
    },

    # ── Template for more cities ───────────────────────────────────────────────
    # "muenchen": {
    #     "db_id": 4,
    #     "name": "München",
    #     "search_terms": [ "Restaurant", ... ],
    #     "locations": [ "München", "Schwabing", ... ],
    #     "min_rating": 4.3,
    #     "min_rating_count": 50,
    #     "search_language": "de",
    #     "search_country": "de",
    # },
}

# ── Backward-compat aliases ────────────────────────────────────────────────────
# pipeline.py imports these by name — no changes needed there.

SEARCH_TERMS     = CITIES["mallorca"]["search_terms"]
LOCATIONS        = CITIES["mallorca"]["locations"]
MIN_RATING       = CITIES["mallorca"]["min_rating"]
MIN_RATING_COUNT = CITIES["mallorca"]["min_rating_count"]

# ── API settings (global, not per-city) ───────────────────────────────────────

SERPER_MAPS_URL   = "https://google.serper.dev/maps"
SERPER_PLACES_URL = "https://google.serper.dev/places"

SEARCH_LANGUAGE  = CITIES["mallorca"]["search_language"]
SEARCH_COUNTRY   = CITIES["mallorca"]["search_country"]
RESULTS_PER_CALL = 20    # max supported by Serper Maps
