-- Migration 013: city_cuisine_labels — per-city distinctive cuisine filter options
-- Generated by: cuisine_city_dna.py --write
-- Run offline after enrichment:
--   docker compose run --rm enricher python cuisine_city_dna.py --write

CREATE TABLE IF NOT EXISTS city_cuisine_labels (
    city_id       INTEGER NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    label         TEXT    NOT NULL,          -- display name (cluster representative)
    cuisine_types TEXT[]  NOT NULL,          -- all raw cuisine_type strings covered
    wpmi          NUMERIC,                   -- wPMI distinctiveness score
    restaurant_n  INTEGER,                  -- restaurants in this city with this label
    pct_of_global INTEGER,                  -- % of global occurrences in this city
    computed_at   TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (city_id, label)
);

CREATE INDEX IF NOT EXISTS city_cuisine_labels_city_idx ON city_cuisine_labels (city_id);
